# Generated by Django 5.2.5 on 2025-11-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_staff_in_analytics', models.BooleanField(default=False, help_text='Include staff in analytics.')),
                ('js_analytics', models.TextField(blank=True, default='', help_text='Javascript to be included before the closing body tag. You should include the script tags.')),
                ('js_head', models.TextField(blank=True, default='', help_text='Javascript to be included in the head tag. You should include the script tags.')),
                ('js_body', models.TextField(blank=True, default='', help_text='Javascript to be included before the closing body tag. You should include the script tags.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
