# Generated by Django 4.2 on 2023-05-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='worker_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='worker_sleep_seconds',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
