# Generated by Django 5.0.7 on 2024-07-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_siteconfiguration_worker_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="js_body",
            field=models.TextField(
                blank=True,
                help_text="Javascript to be included before the closing body "
                "tag. You should include the script tags.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="js_head",
            field=models.TextField(
                blank=True,
                help_text="Javascript to be included in the head tag. You "
                "should include the script tags.",
                null=True,
            ),
        ),
    ]
