# Generated by Django 5.0.7 on 2024-07-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_siteconfiguration_js_body_siteconfiguration_js_head"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="js_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Javascript to be included before the closing body "
                "tag. You should include the script tags.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="js_head",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Javascript to be included in the head tag. "
                "You should include the script tags.",
                null=True,
            ),
        ),
    ]
