# Generated by Django 5.0.7 on 2024-07-29 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_siteconfiguration_js_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerConfiguration",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("sleep_seconds", models.IntegerField(default=10)),
                (
                    "log_level",
                    models.IntegerField(
                        choices=[
                            (10, "DEBUG"),
                            (20, "INFO"),
                            (30, "WARNING"),
                            (40, "ERROR"),
                            (50, "CRITICAL"),
                        ],
                        default=30,
                    ),
                ),
                (
                    "custom",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkerError",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("error", models.TextField()),
                (
                    "error_status",
                    models.CharField(
                        choices=[("O", "Open"), ("C", "Closed")],
                        default="O",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_errors",
                        to="myapp.workerconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
