# Generated by Django 5.1.6 on 2025-03-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_siteconfiguration_required_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='include_staff_in_analytics',
            field=models.BooleanField(default=False, help_text='Include staff in analytics.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='js_analytics',
            field=models.TextField(blank=True, default='', help_text='Javascript to be included before the closing body tag. You should include the script tags.'),
        ),
    ]
