# Generated by Django 5.2.4 on 2025-08-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_siteconfiguration_include_staff_in_analytics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='required_2fa',
        ),
    ]
