# Generated by Django 5.2.4 on 2025-08-20 21:43

from django.db import migrations


def copy_2fa_setting_forward(apps, schema_editor):
    """Copy required_2fa setting from SiteConfiguration to TwoFactorConfig."""
    # Get model classes for this migration point
    SiteConfiguration = apps.get_model('myapp', 'SiteConfiguration')
    TwoFactorConfig = apps.get_model('require2fa', 'TwoFactorConfig')

    # Get the current site configuration (if it exists)
    try:
        site_config = SiteConfiguration.objects.get()
        required_2fa = getattr(site_config, 'required_2fa', False)
    except SiteConfiguration.DoesNotExist:
        # No site configuration exists, default to False
        required_2fa = False

    # Create or update the TwoFactorConfig with the copied value
    TwoFactorConfig.objects.get_or_create(
        defaults={'required': required_2fa}
    )


def copy_2fa_setting_reverse(apps, schema_editor):
    """Reverse migration - copy back from TwoFactorConfig to SiteConfiguration."""
    # Get model classes for this migration point
    SiteConfiguration = apps.get_model('myapp', 'SiteConfiguration')
    TwoFactorConfig = apps.get_model('require2fa', 'TwoFactorConfig')

    # Get the TwoFactorConfig value
    try:
        config = TwoFactorConfig.objects.get()
        required_2fa = config.required
    except TwoFactorConfig.DoesNotExist:
        required_2fa = False

    # Update SiteConfiguration if it exists
    try:
        site_config = SiteConfiguration.objects.get()
        site_config.required_2fa = required_2fa
        site_config.save()
    except SiteConfiguration.DoesNotExist:
        # If no SiteConfiguration exists, we can't copy back
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('require2fa', '0001_initial'),
        ('myapp', '0008_siteconfiguration_include_staff_in_analytics_and_more'),  # Latest myapp migration
    ]

    operations = [
        migrations.RunPython(
            copy_2fa_setting_forward,
            copy_2fa_setting_reverse
        ),
    ]
