# Generated by Django 5.2.5 on 2025-11-18 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('file_count', models.IntegerField(help_text='Number of files included in the zip')),
                ('total_bytes', models.BigIntegerField(help_text='Total size of all files in bytes')),
                ('downloaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_downloads', to=settings.AUTH_USER_MODEL)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_downloads', to='dataroom.dataendpoint')),
            ],
            options={
                'verbose_name': 'Bulk Download',
                'verbose_name_plural': 'Bulk Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
