# Generated by Django 5.1 on 2024-09-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_invitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="invite_key",
            field=models.UUIDField(unique=True),
        ),
    ]
